In [1]:
# IMPORT NECESSARY LIBRARIES AND DATA
import pandas as pd
import numpy as np
arr = np.arange(72).reshape(9, 8)
data_url = 'https://raw.githubusercontent.com/plotly/datasets/master/mpg_2017.txt'
mpg_df = pd.read_csv(data_url, sep='\t')
mpg_df.head()

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
5         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

Goals
1. Determine the shape, number of dimensions and type of elements in the numpy array arr
2. Determine the median of all elements in arr
3. Determine the position (not the value) of the maximum value element in arr
4. Create an array of the same shape as arr but filled with zeros
5. Create an array of the same shape as arr but filled with ones
6. Create an array of the same shape as arr but where all elements are the square root values
7. Create an array result of shape 9 by 9 resulting from multiplication of arr with transpose(arr). Hint: use np.dot

In [2]:
# YOUR SECTION A ANSWER HERE (please use comments to number each of your answers)
np.set_printoptions(linewidth=np.inf)
#1
print('\n', 'Shape of arr is: ', arr.shape, '\n', 'Number of dimensions in arr are: ', arr.ndim, '\n', 'Type of elements in arr is: ' , type(arr.ndim),'\n','--------')
#2
print('\n \n', 'Median of all elements in arr is: ', np.median(arr), '\n', '--------')
#3
print('\n \n' , 'Position of max value element in arr is: ', np.where(arr == np.amax(arr)), '\n', '--------')
#4
arrZero = np.zeros(arr.shape, dtype = int)
print('\n \n', 'Numpy zeros array with the shape same as the array arr looks like \n', arrZero, '\n', '--------')
#5
arrOnes = np.ones(arr.shape, dtype = int)
print('\n \n', 'Numpy ones array with the shape same as the array arr looks like \n', arrOnes, '\n', '--------')
#6
arrSqrt = np.sqrt(arr)
print('\n \n', 'A square root array of arr is \n', arrSqrt, '\n', '--------')
#7
arrMult = np.dot(arr,np.transpose(arr))
print('\n \n', 'Matrix multiplication of arr and transpose of arr \n', arrMult, '\n')


 Shape of arr is:  (9, 8) 
 Number of dimensions in arr are:  2 
 Type of elements in arr is:  <class 'int'> 
 --------

 
 Median of all elements in arr is:  35.5 
 --------

 
 Position of max value element in arr is:  (array([8]), array([7])) 
 --------

 
 Numpy zeros array with the shape same as the array arr looks like 
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]] 
 --------

 
 Numpy ones array with the shape same as the array arr looks like 
 [[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]] 
 --------

 
 A square root array of arr is 
 [[0.         1.         1.41421356 1.73205081 2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479 3.46410162 3.60555128 3.74165739 3.87298335]
 [4.         4.

Goals

The dataframe `mpg_df` loads the dataset that contains information on various car makes and models over a number years along with information on their engine specifications, including their MPG (miles-per-gallon) rating for both `cty` (city driving) and `hwy` (highway driving)
The dataset has already been loaded for you in the first code cell above.
 1. Print the number of rows of the dataframe
 2. Print the names of all the columns of the dataframe
 3. Print the 20th row of the dataframe
 4. Which is the most fuel efficient car in the `compact` class in the whole dataset?
 5. Which is the most fuel efficient 6 cylinder car make/model made after 2003?
 6. Which is Subaru's least fuel efficient model in the whole dataset?
 7. Which is the worst fuel efficient model/make in the `suv` class?


In [3]:
#1
print('\n', 'Number of rows in the datafrmae mpg_df is: ', len(mpg_df.index), '\n')
print('Confirming the shape of the dataframe: ', mpg_df.shape, '\n', '--------')
#2
print('\n \n', 'Column names are ', [col for col in mpg_df], '\n', '--------')
#3
print('\n \n', '20th row in the datafrmae is \n', mpg_df.iloc[19], '\n', '--------')
pd.set_option('display.expand_frame_repr', False)
#4
print("\n Column named class is renamed to cls. class is a keyword in python; there were errors when accessed with the name class \n")
mpg_df.rename(columns={"class":"cls"}, inplace = True)
#Creating a dataframe with only compact class rows
compactCls = mpg_df.query('cls=="compact"')
print('\n \n', 'Most fuel efficient car in city and highway under compact class') 
cmptCar = compactCls[(compactCls.cty == compactCls['cty'].max())]
print(cmptCar,'\n', '--------')
#5
print('\n \n', 'Most fuel efficient 6 cylinder car in highway, built year after 2003') 
cly6 = mpg_df.query('cyl == 6 and year > 2003')
highway = cly6[((cly6.hwy == cly6['hwy'].max()))]
print(highway,'\n', '--------')
print('\n \n', 'Most fuel efficient 6 cylinder cars in city, built year after 2003') 
city = cly6[((cly6.cty == cly6['cty'].max()))]
print(city,'\n', '--------')
print('\n \n', 'Least fuel efficient car of Subaru') 
subaru = mpg_df.query('manufacturer=="subaru"')
saubLest = subaru[((subaru.hwy == subaru['hwy'].min()))]
print(saubLest,'\n', '--------')
print('\n \n', 'Least fuel efficient suv in the whole of dataset') 
suvs = mpg_df.query('cls=="suv"')
suvsLeast = suvs[((suvs.hwy == suvs['hwy'].min()))].filter(['manufacturer','model'])


 Number of rows in the datafrmae mpg_df is:  234 

Confirming the shape of the dataframe:  (234, 11) 
 --------

 
 Column names are  ['manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'] 
 --------

 
 20th row in the datafrmae is 
 manufacturer             chevrolet
model           c1500 suburban 2wd
displ                          5.3
year                          2008
cyl                              8
trans                     auto(l4)
drv                              r
cty                             11
hwy                             15
fl                               e
class                          suv
Name: 20, dtype: object 
 --------

 Column named class is renamed to cls. class is a keyword in python; there were errors when accessed with the name class 


 
 Most fuel efficient car in city and highway under compact class
    manufacturer  model  displ  year  cyl       trans drv  cty  hwy fl      cls
213   volkswagen  jetta    1.9  